/*
This is automatically generated file.
DO NOT EDIT THIS FILE.
*/
#pragma once
#include <CoreMinimal.h>
UENUM(BlueprintType)
enum class EDropDataId : uint8
{
	NewRow,
	Invalid
};
static constexpr uint8 DropDataIdSize = static_cast<uint8>(EDropDataId::Invalid);
inline bool IsInvalid(const EDropDataId id) { return static_cast<uint8>(id) >= DropDataIdSize; }
