/*
This is automatically generated file.
DO NOT EDIT THIS FILE.
*/
#pragma once
#include <CoreMinimal.h>
UENUM(BlueprintType)
enum class EItemDataId : uint8
{
	EnergyCapacitor,
	BurstCore,
	FlagGrenade,
	HealthPack,
	RespawnChip,
	Invalid
};
static constexpr uint8 ItemDataIdSize = static_cast<uint8>(EItemDataId::Invalid);
inline bool IsInvalid(const EItemDataId id) { return static_cast<uint8>(id) >= ItemDataIdSize; }
