/*
This is automatically generated file.
DO NOT EDIT THIS FILE.
*/
#pragma once
#include <CoreMinimal.h>
UENUM(BlueprintType)
enum class EWeaponDataId : uint8
{
	Handgun,
	SubmachineGun,
	Shotgun,
	SniperRifle,
	Launcher,
	ToyGun,
	Invalid
};
static constexpr uint8 WeaponDataIdSize = static_cast<uint8>(EWeaponDataId::Invalid);
inline bool IsInvalid(const EWeaponDataId id) { return static_cast<uint8>(id) >= WeaponDataIdSize; }
